contacts_home:
    pattern:  /contacts/home
    defaults: { _controller: "AbookBundle:Contacts:index" }

contacts_list:
    pattern:  /contacts/list
    defaults: { _controller: "AbookBundle:Contacts:index" }

contacts_show:
    pattern:  /contacts/{id}/show
    defaults: { _controller: "AbookBundle:Contacts:show" }

contacts_new:
    pattern:  /contacts/new
    defaults: { _controller: "AbookBundle:Contacts:new" }

contacts_create:
    pattern:  /contacts/create
    defaults: { _controller: "AbookBundle:Contacts:create" }
    requirements: { _method: post }

contacts_edit:
    pattern:  /contacts/{id}/edit
    defaults: { _controller: "AbookBundle:Contacts:edit" }

contacts_update:
    pattern:  /contacts/{id}/update
    defaults: { _controller: "AbookBundle:Contacts:update" }
    requirements: { _method: post|put }

contacts_delete:
    pattern:  /contacts/{id}/delete
    defaults: { _controller: "AbookBundle:Contacts:delete" }
    requirements: { _method: post|delete }